# Edit the script to suit your use.
# Cretae the file: touch dev-cluster-secret.yaml
# Edit to your Target cluster Name, Target Cluster API URL, Target cluster service Account Token.
# Apply it : kubectl apply -f dev-cluster-secret.yaml -n argocd

# ===================================

apiVersion: v1
kind: Secret
metadata:
  name: my-remote-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "my-target-cluster-name"
  server: "https://<TARGET_CLUSTER_API_SERVER_IP_OR_URL>:6443"
  config: |
    {
      "bearerToken": "<SERVICE_ACCOUNT_TOKEN_FROM_TARGET_CLUSTER>",
      "tlsClientConfig": {
        "insecure": true
      }
    }
